### ISSUE TITLE
Error upon calling DAuthSDK init

### ISSUE THREAD

**Issue by yaizudamashii** [SIVIRA/dauth-sdk-js#4]
I have the following code

```
const DAuthSDK = require('dauth-sdk');
const crypto = require('crypto');

module.exports = class DAuthManager {

    constructor({postAuthRedirectURL, env}) {
        this.redirectURL = postAuthRedirectURL;

        /** @private */
        this.clientID = 'client_id';
        
        this.env = env || 'dev';
    }

    authenticate() {
        const nonce = crypto.randomBytes(16).toString('hex');
        DAuthSDK.DAuth.init({
            clientID: this.clientID,
            env: this.env
        }).then((dAuth) => {
            dAuth.authorize({
                redirectURL: this.postAuthRedirectURL,
                nonce: nonce,
            });
        });
    }

   /..../
};
```

but when I initialize DAuthManager and call authenticate, I am getting an error as below:

```
ReferenceError: WebSocket is not defined
    at /Users/yuki/Developer/Ghost/node_modules/dauth-sdk/dist/dauth.js:26:47
    at new Promise (<anonymous>)
    at Function.DAuth.init (/Users/yuki/Developer/Ghost/node_modules/dauth-sdk/dist/dauth.js:17:16)
    at DAuthManager.authenticate (/Users/yuki/Developer/Ghost/node_modules/members-api/packages/members-api/lib/services/dauth-manager.js:17:24)
    at Object.authenticateWithDAuth (/Users/yuki/Developer/Ghost/node_modules/members-api/packages/members-api/lib/MembersAPI.js:343:22)
```

It looks like it is an error in the SDK could someone take a look?

**Comment by m0t0k1ch1** [comment]
[WebSocket API seems to be supported by most modern browsers.](https://developer.mozilla.org/ja/docs/Web/API/WebSockets_API) Could you tell me which browser you are using and its version?

**Comment by m0t0k1ch1** [comment]
@yaizudamashii Thank you for reporting the problem.

However, [WebSocket API seems to be supported by most modern browsers.](https://developer.mozilla.org/ja/docs/Web/API/WebSockets_API) Could you tell me which browser you are using and its version?

**Comment by m0t0k1ch1** [comment]
@yaizudamashii Thank you for reporting the issue.

However, dauth-sdk-js is intended to work in browsers ([the WebSocket API is supported by most modern browsers](https://developer.mozilla.org/ja/docs/Web/API/WebSockets_API)). It is not intended to be used with Node.js.

**Comment by yaizudamashii** [comment]
It worked from the browser, thank you.  I think it'd be nice to update the documentation.
